"""
tmLQCD vec_times_vec, vectorized over lattice sites
==========================================================
vec times vec: the color-vector scalar product sum_c conj(a.c) * b.c

Generated by gen_rvv_lqcd.py (see there for the sources). One lattice site per
lane; every real or imaginary part is a 64-lane f32 vector, one LMUL8
register group at VLEN 256, loaded from plane p of a structure-of-arrays field
(field_ptr + p * n_sites + site). Inputs are small nonzero integers so the
float results are exact and the torch reference matches bit for bit.
"""

import torch

import triton
import triton.language as tl

CPU_BLOCK_SIZE = 64


@triton.jit
def lqcd_vec_times_vec_kernel(a_ptr, b_ptr, out_ptr, n_sites, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    site = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = site < n_sites

    a_0 = tl.load(a_ptr + 0 * n_sites + site, mask=mask)
    b_0 = tl.load(b_ptr + 0 * n_sites + site, mask=mask)
    t1 = a_0 * b_0
    a_1 = tl.load(a_ptr + 1 * n_sites + site, mask=mask)
    b_1 = tl.load(b_ptr + 1 * n_sites + site, mask=mask)
    t2 = a_1 * b_1
    t3 = t1 + t2
    t4 = a_0 * b_1
    t5 = a_1 * b_0
    t6 = t4 - t5
    a_2 = tl.load(a_ptr + 2 * n_sites + site, mask=mask)
    b_2 = tl.load(b_ptr + 2 * n_sites + site, mask=mask)
    t7 = a_2 * b_2
    a_3 = tl.load(a_ptr + 3 * n_sites + site, mask=mask)
    b_3 = tl.load(b_ptr + 3 * n_sites + site, mask=mask)
    t8 = a_3 * b_3
    t9 = t7 + t8
    t10 = a_2 * b_3
    t11 = a_3 * b_2
    t12 = t10 - t11
    t13 = t3 + t9
    t14 = t6 + t12
    a_4 = tl.load(a_ptr + 4 * n_sites + site, mask=mask)
    b_4 = tl.load(b_ptr + 4 * n_sites + site, mask=mask)
    t15 = a_4 * b_4
    a_5 = tl.load(a_ptr + 5 * n_sites + site, mask=mask)
    b_5 = tl.load(b_ptr + 5 * n_sites + site, mask=mask)
    t16 = a_5 * b_5
    t17 = t15 + t16
    t18 = a_4 * b_5
    t19 = a_5 * b_4
    t20 = t18 - t19
    t21 = t13 + t17
    t22 = t14 + t20
    tl.store(out_ptr + 0 * n_sites + site, t21, mask=mask)
    tl.store(out_ptr + 1 * n_sites + site, t22, mask=mask)


torch.manual_seed(0)
n_sites = 4096
triton.runtime.driver.set_active_to_cpu()
values = torch.tensor([-3.0, -2.0, -1.0, 1.0, 2.0, 3.0])
a = values[torch.randint(0, len(values), (6, n_sites))]
b = values[torch.randint(0, len(values), (6, n_sites))]

from triton.backends.cpu.riscv import compile_deploy_and_run

RISCV_HOST = "chlee@140.114.78.64"
RISCV_REMOTE_DIR = "~/triton-riscv-elf"


def reference():

    a_0 = a[0]
    b_0 = b[0]
    t1 = a_0 * b_0
    a_1 = a[1]
    b_1 = b[1]
    t2 = a_1 * b_1
    t3 = t1 + t2
    t4 = a_0 * b_1
    t5 = a_1 * b_0
    t6 = t4 - t5
    a_2 = a[2]
    b_2 = b[2]
    t7 = a_2 * b_2
    a_3 = a[3]
    b_3 = b[3]
    t8 = a_3 * b_3
    t9 = t7 + t8
    t10 = a_2 * b_3
    t11 = a_3 * b_2
    t12 = t10 - t11
    t13 = t3 + t9
    t14 = t6 + t12
    a_4 = a[4]
    b_4 = b[4]
    t15 = a_4 * b_4
    a_5 = a[5]
    b_5 = b[5]
    t16 = a_5 * b_5
    t17 = t15 + t16
    t18 = a_4 * b_5
    t19 = a_5 * b_4
    t20 = t18 - t19
    t21 = t13 + t17
    t22 = t14 + t20
    return torch.stack([t21, t22])


def run_on_board(kernel, constexprs, name):
    expected = reference().reshape(-1)
    arguments = {
        "a_ptr": a.reshape(-1).tolist(),
        "b_ptr": b.reshape(-1).tolist(),
        "out_ptr": [0.0] * (2 * n_sites),
        "n_sites": n_sites,

    }
    grid = (triton.cdiv(n_sites, CPU_BLOCK_SIZE), )
    result = compile_deploy_and_run(kernel, arguments, grid, f"artifacts/riscv/{name}.elf", RISCV_HOST,
                                     constexprs=constexprs, expected={"out_ptr": expected.tolist()},
                                     remote_dir=RISCV_REMOTE_DIR)
    print(f"{name}:")
    print(result.stdout, end="")
    print(result.stderr, end="")


run_on_board(lqcd_vec_times_vec_kernel, {"BLOCK_SIZE": CPU_BLOCK_SIZE}, "rvv-lqcd-vec-times-vec")
