"""
tmLQCD su3_inverse_multiply, vectorized over lattice sites
=================================================================
_su3_inverse_multiply(r, u, s): r = u^dagger * s

Generated by gen_rvv_lqcd.py (see there for the sources). One lattice site per
lane; every real or imaginary part is a 64-lane f32 vector, one LMUL8
register group at VLEN 256, loaded from plane p of a structure-of-arrays field
(field_ptr + p * n_sites + site). Inputs are small nonzero integers so the
float results are exact and the torch reference matches bit for bit.
"""

import torch

import triton
import triton.language as tl

CPU_BLOCK_SIZE = 64


@triton.jit
def lqcd_su3_inverse_multiply_kernel(u_ptr, s_ptr, out_ptr, n_sites, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    site = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = site < n_sites

    u_0 = tl.load(u_ptr + 0 * n_sites + site, mask=mask)
    s_0 = tl.load(s_ptr + 0 * n_sites + site, mask=mask)
    t1 = u_0 * s_0
    u_1 = tl.load(u_ptr + 1 * n_sites + site, mask=mask)
    s_1 = tl.load(s_ptr + 1 * n_sites + site, mask=mask)
    t2 = u_1 * s_1
    t3 = t1 + t2
    t4 = u_0 * s_1
    t5 = u_1 * s_0
    t6 = t4 - t5
    u_6 = tl.load(u_ptr + 6 * n_sites + site, mask=mask)
    s_2 = tl.load(s_ptr + 2 * n_sites + site, mask=mask)
    t7 = u_6 * s_2
    u_7 = tl.load(u_ptr + 7 * n_sites + site, mask=mask)
    s_3 = tl.load(s_ptr + 3 * n_sites + site, mask=mask)
    t8 = u_7 * s_3
    t9 = t7 + t8
    t10 = u_6 * s_3
    t11 = u_7 * s_2
    t12 = t10 - t11
    t13 = t3 + t9
    t14 = t6 + t12
    u_12 = tl.load(u_ptr + 12 * n_sites + site, mask=mask)
    s_4 = tl.load(s_ptr + 4 * n_sites + site, mask=mask)
    t15 = u_12 * s_4
    u_13 = tl.load(u_ptr + 13 * n_sites + site, mask=mask)
    s_5 = tl.load(s_ptr + 5 * n_sites + site, mask=mask)
    t16 = u_13 * s_5
    t17 = t15 + t16
    t18 = u_12 * s_5
    t19 = u_13 * s_4
    t20 = t18 - t19
    t21 = t13 + t17
    t22 = t14 + t20
    u_2 = tl.load(u_ptr + 2 * n_sites + site, mask=mask)
    t23 = u_2 * s_0
    u_3 = tl.load(u_ptr + 3 * n_sites + site, mask=mask)
    t24 = u_3 * s_1
    t25 = t23 + t24
    t26 = u_2 * s_1
    t27 = u_3 * s_0
    t28 = t26 - t27
    u_8 = tl.load(u_ptr + 8 * n_sites + site, mask=mask)
    t29 = u_8 * s_2
    u_9 = tl.load(u_ptr + 9 * n_sites + site, mask=mask)
    t30 = u_9 * s_3
    t31 = t29 + t30
    t32 = u_8 * s_3
    t33 = u_9 * s_2
    t34 = t32 - t33
    t35 = t25 + t31
    t36 = t28 + t34
    u_14 = tl.load(u_ptr + 14 * n_sites + site, mask=mask)
    t37 = u_14 * s_4
    u_15 = tl.load(u_ptr + 15 * n_sites + site, mask=mask)
    t38 = u_15 * s_5
    t39 = t37 + t38
    t40 = u_14 * s_5
    t41 = u_15 * s_4
    t42 = t40 - t41
    t43 = t35 + t39
    t44 = t36 + t42
    u_4 = tl.load(u_ptr + 4 * n_sites + site, mask=mask)
    t45 = u_4 * s_0
    u_5 = tl.load(u_ptr + 5 * n_sites + site, mask=mask)
    t46 = u_5 * s_1
    t47 = t45 + t46
    t48 = u_4 * s_1
    t49 = u_5 * s_0
    t50 = t48 - t49
    u_10 = tl.load(u_ptr + 10 * n_sites + site, mask=mask)
    t51 = u_10 * s_2
    u_11 = tl.load(u_ptr + 11 * n_sites + site, mask=mask)
    t52 = u_11 * s_3
    t53 = t51 + t52
    t54 = u_10 * s_3
    t55 = u_11 * s_2
    t56 = t54 - t55
    t57 = t47 + t53
    t58 = t50 + t56
    u_16 = tl.load(u_ptr + 16 * n_sites + site, mask=mask)
    t59 = u_16 * s_4
    u_17 = tl.load(u_ptr + 17 * n_sites + site, mask=mask)
    t60 = u_17 * s_5
    t61 = t59 + t60
    t62 = u_16 * s_5
    t63 = u_17 * s_4
    t64 = t62 - t63
    t65 = t57 + t61
    t66 = t58 + t64
    tl.store(out_ptr + 0 * n_sites + site, t21, mask=mask)
    tl.store(out_ptr + 1 * n_sites + site, t22, mask=mask)
    tl.store(out_ptr + 2 * n_sites + site, t43, mask=mask)
    tl.store(out_ptr + 3 * n_sites + site, t44, mask=mask)
    tl.store(out_ptr + 4 * n_sites + site, t65, mask=mask)
    tl.store(out_ptr + 5 * n_sites + site, t66, mask=mask)


torch.manual_seed(0)
n_sites = 4096
triton.runtime.driver.set_active_to_cpu()
values = torch.tensor([-3.0, -2.0, -1.0, 1.0, 2.0, 3.0])
u = values[torch.randint(0, len(values), (18, n_sites))]
s = values[torch.randint(0, len(values), (6, n_sites))]

from triton.backends.cpu.riscv import compile_deploy_and_run

RISCV_HOST = "chlee@140.114.78.64"
RISCV_REMOTE_DIR = "~/triton-riscv-elf"


def reference():

    u_0 = u[0]
    s_0 = s[0]
    t1 = u_0 * s_0
    u_1 = u[1]
    s_1 = s[1]
    t2 = u_1 * s_1
    t3 = t1 + t2
    t4 = u_0 * s_1
    t5 = u_1 * s_0
    t6 = t4 - t5
    u_6 = u[6]
    s_2 = s[2]
    t7 = u_6 * s_2
    u_7 = u[7]
    s_3 = s[3]
    t8 = u_7 * s_3
    t9 = t7 + t8
    t10 = u_6 * s_3
    t11 = u_7 * s_2
    t12 = t10 - t11
    t13 = t3 + t9
    t14 = t6 + t12
    u_12 = u[12]
    s_4 = s[4]
    t15 = u_12 * s_4
    u_13 = u[13]
    s_5 = s[5]
    t16 = u_13 * s_5
    t17 = t15 + t16
    t18 = u_12 * s_5
    t19 = u_13 * s_4
    t20 = t18 - t19
    t21 = t13 + t17
    t22 = t14 + t20
    u_2 = u[2]
    t23 = u_2 * s_0
    u_3 = u[3]
    t24 = u_3 * s_1
    t25 = t23 + t24
    t26 = u_2 * s_1
    t27 = u_3 * s_0
    t28 = t26 - t27
    u_8 = u[8]
    t29 = u_8 * s_2
    u_9 = u[9]
    t30 = u_9 * s_3
    t31 = t29 + t30
    t32 = u_8 * s_3
    t33 = u_9 * s_2
    t34 = t32 - t33
    t35 = t25 + t31
    t36 = t28 + t34
    u_14 = u[14]
    t37 = u_14 * s_4
    u_15 = u[15]
    t38 = u_15 * s_5
    t39 = t37 + t38
    t40 = u_14 * s_5
    t41 = u_15 * s_4
    t42 = t40 - t41
    t43 = t35 + t39
    t44 = t36 + t42
    u_4 = u[4]
    t45 = u_4 * s_0
    u_5 = u[5]
    t46 = u_5 * s_1
    t47 = t45 + t46
    t48 = u_4 * s_1
    t49 = u_5 * s_0
    t50 = t48 - t49
    u_10 = u[10]
    t51 = u_10 * s_2
    u_11 = u[11]
    t52 = u_11 * s_3
    t53 = t51 + t52
    t54 = u_10 * s_3
    t55 = u_11 * s_2
    t56 = t54 - t55
    t57 = t47 + t53
    t58 = t50 + t56
    u_16 = u[16]
    t59 = u_16 * s_4
    u_17 = u[17]
    t60 = u_17 * s_5
    t61 = t59 + t60
    t62 = u_16 * s_5
    t63 = u_17 * s_4
    t64 = t62 - t63
    t65 = t57 + t61
    t66 = t58 + t64
    return torch.stack([t21, t22, t43, t44, t65, t66])


def run_on_board(kernel, constexprs, name):
    expected = reference().reshape(-1)
    arguments = {
        "u_ptr": u.reshape(-1).tolist(),
        "s_ptr": s.reshape(-1).tolist(),
        "out_ptr": [0.0] * (6 * n_sites),
        "n_sites": n_sites,

    }
    grid = (triton.cdiv(n_sites, CPU_BLOCK_SIZE), )
    result = compile_deploy_and_run(kernel, arguments, grid, f"artifacts/riscv/{name}.elf", RISCV_HOST,
                                     constexprs=constexprs, expected={"out_ptr": expected.tolist()},
                                     remote_dir=RISCV_REMOTE_DIR)
    print(f"{name}:")
    print(result.stdout, end="")
    print(result.stderr, end="")


run_on_board(lqcd_su3_inverse_multiply_kernel, {"BLOCK_SIZE": CPU_BLOCK_SIZE}, "rvv-lqcd-su3-inverse-multiply")
