"""
tmLQCD complex_times_vector, vectorized over lattice sites
=================================================================
_complex_times_vector(x, c, y): x = c * y, c a per-site complex

Generated by gen_rvv_lqcd.py (see there for the sources). One lattice site per
lane; every real or imaginary part is a 64-lane f32 vector, one LMUL8
register group at VLEN 256, loaded from plane p of a structure-of-arrays field
(field_ptr + p * n_sites + site). Inputs are small nonzero integers so the
float results are exact and the torch reference matches bit for bit.
"""

import torch

import triton
import triton.language as tl

CPU_BLOCK_SIZE = 64


@triton.jit
def lqcd_complex_times_vector_kernel(c_ptr, y_ptr, out_ptr, n_sites, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    site = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = site < n_sites

    c_0 = tl.load(c_ptr + 0 * n_sites + site, mask=mask)
    y_0 = tl.load(y_ptr + 0 * n_sites + site, mask=mask)
    t1 = c_0 * y_0
    c_1 = tl.load(c_ptr + 1 * n_sites + site, mask=mask)
    y_1 = tl.load(y_ptr + 1 * n_sites + site, mask=mask)
    t2 = c_1 * y_1
    t3 = t1 - t2
    t4 = c_0 * y_1
    t5 = c_1 * y_0
    t6 = t4 + t5
    y_2 = tl.load(y_ptr + 2 * n_sites + site, mask=mask)
    t7 = c_0 * y_2
    y_3 = tl.load(y_ptr + 3 * n_sites + site, mask=mask)
    t8 = c_1 * y_3
    t9 = t7 - t8
    t10 = c_0 * y_3
    t11 = c_1 * y_2
    t12 = t10 + t11
    y_4 = tl.load(y_ptr + 4 * n_sites + site, mask=mask)
    t13 = c_0 * y_4
    y_5 = tl.load(y_ptr + 5 * n_sites + site, mask=mask)
    t14 = c_1 * y_5
    t15 = t13 - t14
    t16 = c_0 * y_5
    t17 = c_1 * y_4
    t18 = t16 + t17
    tl.store(out_ptr + 0 * n_sites + site, t3, mask=mask)
    tl.store(out_ptr + 1 * n_sites + site, t6, mask=mask)
    tl.store(out_ptr + 2 * n_sites + site, t9, mask=mask)
    tl.store(out_ptr + 3 * n_sites + site, t12, mask=mask)
    tl.store(out_ptr + 4 * n_sites + site, t15, mask=mask)
    tl.store(out_ptr + 5 * n_sites + site, t18, mask=mask)


torch.manual_seed(0)
n_sites = 4096
triton.runtime.driver.set_active_to_cpu()
values = torch.tensor([-3.0, -2.0, -1.0, 1.0, 2.0, 3.0])
c = values[torch.randint(0, len(values), (2, n_sites))]
y = values[torch.randint(0, len(values), (6, n_sites))]

from triton.backends.cpu.riscv import compile_deploy_and_run

RISCV_HOST = "chlee@140.114.78.64"
RISCV_REMOTE_DIR = "~/triton-riscv-elf"


def reference():

    c_0 = c[0]
    y_0 = y[0]
    t1 = c_0 * y_0
    c_1 = c[1]
    y_1 = y[1]
    t2 = c_1 * y_1
    t3 = t1 - t2
    t4 = c_0 * y_1
    t5 = c_1 * y_0
    t6 = t4 + t5
    y_2 = y[2]
    t7 = c_0 * y_2
    y_3 = y[3]
    t8 = c_1 * y_3
    t9 = t7 - t8
    t10 = c_0 * y_3
    t11 = c_1 * y_2
    t12 = t10 + t11
    y_4 = y[4]
    t13 = c_0 * y_4
    y_5 = y[5]
    t14 = c_1 * y_5
    t15 = t13 - t14
    t16 = c_0 * y_5
    t17 = c_1 * y_4
    t18 = t16 + t17
    return torch.stack([t3, t6, t9, t12, t15, t18])


def run_on_board(kernel, constexprs, name):
    expected = reference().reshape(-1)
    arguments = {
        "c_ptr": c.reshape(-1).tolist(),
        "y_ptr": y.reshape(-1).tolist(),
        "out_ptr": [0.0] * (6 * n_sites),
        "n_sites": n_sites,

    }
    grid = (triton.cdiv(n_sites, CPU_BLOCK_SIZE), )
    result = compile_deploy_and_run(kernel, arguments, grid, f"artifacts/riscv/{name}.elf", RISCV_HOST,
                                     constexprs=constexprs, expected={"out_ptr": expected.tolist()},
                                     remote_dir=RISCV_REMOTE_DIR)
    print(f"{name}:")
    print(result.stdout, end="")
    print(result.stderr, end="")


run_on_board(lqcd_complex_times_vector_kernel, {"BLOCK_SIZE": CPU_BLOCK_SIZE}, "rvv-lqcd-complex-times-vector")
