"""
tmLQCD hop_t_p, vectorized over lattice sites
====================================================
Hopping_Matrix loop k body, _hop_t_p (src/lib/operator/hopping.h):
    psi = sp.s0 + sp.s2; chi = u * psi; psi = ka0 * chi; temp.s0 = temp.s2 = psi
    psi = sp.s1 + sp.s3; chi = u * psi; psi = ka0 * chi; temp.s1 = temp.s3 = psi
The link u is used by both halves.

Generated by gen_rvv_lqcd.py (see there for the sources). One lattice site per
lane; every real or imaginary part is a 64-lane f32 vector, one LMUL8
register group at VLEN 256, loaded from plane p of a structure-of-arrays field
(field_ptr + p * n_sites + site). Inputs are small nonzero integers so the
float results are exact and the torch reference matches bit for bit.
"""

import torch

import triton
import triton.language as tl

CPU_BLOCK_SIZE = 64


@triton.jit
def lqcd_hop_t_p_kernel(sp_ptr, u_ptr, out_ptr, n_sites, ka0_re, ka0_im, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    site = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = site < n_sites

    sp_0 = tl.load(sp_ptr + 0 * n_sites + site, mask=mask)
    sp_12 = tl.load(sp_ptr + 12 * n_sites + site, mask=mask)
    t1 = sp_0 + sp_12
    sp_1 = tl.load(sp_ptr + 1 * n_sites + site, mask=mask)
    sp_13 = tl.load(sp_ptr + 13 * n_sites + site, mask=mask)
    t2 = sp_1 + sp_13
    sp_2 = tl.load(sp_ptr + 2 * n_sites + site, mask=mask)
    sp_14 = tl.load(sp_ptr + 14 * n_sites + site, mask=mask)
    t3 = sp_2 + sp_14
    sp_3 = tl.load(sp_ptr + 3 * n_sites + site, mask=mask)
    sp_15 = tl.load(sp_ptr + 15 * n_sites + site, mask=mask)
    t4 = sp_3 + sp_15
    sp_4 = tl.load(sp_ptr + 4 * n_sites + site, mask=mask)
    sp_16 = tl.load(sp_ptr + 16 * n_sites + site, mask=mask)
    t5 = sp_4 + sp_16
    sp_5 = tl.load(sp_ptr + 5 * n_sites + site, mask=mask)
    sp_17 = tl.load(sp_ptr + 17 * n_sites + site, mask=mask)
    t6 = sp_5 + sp_17
    u_0 = tl.load(u_ptr + 0 * n_sites + site, mask=mask)
    t7 = u_0 * t1
    u_1 = tl.load(u_ptr + 1 * n_sites + site, mask=mask)
    t8 = u_1 * t2
    t9 = t7 - t8
    t10 = u_0 * t2
    t11 = u_1 * t1
    t12 = t10 + t11
    u_2 = tl.load(u_ptr + 2 * n_sites + site, mask=mask)
    t13 = u_2 * t3
    u_3 = tl.load(u_ptr + 3 * n_sites + site, mask=mask)
    t14 = u_3 * t4
    t15 = t13 - t14
    t16 = u_2 * t4
    t17 = u_3 * t3
    t18 = t16 + t17
    t19 = t9 + t15
    t20 = t12 + t18
    u_4 = tl.load(u_ptr + 4 * n_sites + site, mask=mask)
    t21 = u_4 * t5
    u_5 = tl.load(u_ptr + 5 * n_sites + site, mask=mask)
    t22 = u_5 * t6
    t23 = t21 - t22
    t24 = u_4 * t6
    t25 = u_5 * t5
    t26 = t24 + t25
    t27 = t19 + t23
    t28 = t20 + t26
    u_6 = tl.load(u_ptr + 6 * n_sites + site, mask=mask)
    t29 = u_6 * t1
    u_7 = tl.load(u_ptr + 7 * n_sites + site, mask=mask)
    t30 = u_7 * t2
    t31 = t29 - t30
    t32 = u_6 * t2
    t33 = u_7 * t1
    t34 = t32 + t33
    u_8 = tl.load(u_ptr + 8 * n_sites + site, mask=mask)
    t35 = u_8 * t3
    u_9 = tl.load(u_ptr + 9 * n_sites + site, mask=mask)
    t36 = u_9 * t4
    t37 = t35 - t36
    t38 = u_8 * t4
    t39 = u_9 * t3
    t40 = t38 + t39
    t41 = t31 + t37
    t42 = t34 + t40
    u_10 = tl.load(u_ptr + 10 * n_sites + site, mask=mask)
    t43 = u_10 * t5
    u_11 = tl.load(u_ptr + 11 * n_sites + site, mask=mask)
    t44 = u_11 * t6
    t45 = t43 - t44
    t46 = u_10 * t6
    t47 = u_11 * t5
    t48 = t46 + t47
    t49 = t41 + t45
    t50 = t42 + t48
    u_12 = tl.load(u_ptr + 12 * n_sites + site, mask=mask)
    t51 = u_12 * t1
    u_13 = tl.load(u_ptr + 13 * n_sites + site, mask=mask)
    t52 = u_13 * t2
    t53 = t51 - t52
    t54 = u_12 * t2
    t55 = u_13 * t1
    t56 = t54 + t55
    u_14 = tl.load(u_ptr + 14 * n_sites + site, mask=mask)
    t57 = u_14 * t3
    u_15 = tl.load(u_ptr + 15 * n_sites + site, mask=mask)
    t58 = u_15 * t4
    t59 = t57 - t58
    t60 = u_14 * t4
    t61 = u_15 * t3
    t62 = t60 + t61
    t63 = t53 + t59
    t64 = t56 + t62
    u_16 = tl.load(u_ptr + 16 * n_sites + site, mask=mask)
    t65 = u_16 * t5
    u_17 = tl.load(u_ptr + 17 * n_sites + site, mask=mask)
    t66 = u_17 * t6
    t67 = t65 - t66
    t68 = u_16 * t6
    t69 = u_17 * t5
    t70 = t68 + t69
    t71 = t63 + t67
    t72 = t64 + t70
    t73 = ka0_re * t27
    t74 = ka0_im * t28
    t75 = t73 - t74
    t76 = ka0_re * t28
    t77 = ka0_im * t27
    t78 = t76 + t77
    t79 = ka0_re * t49
    t80 = ka0_im * t50
    t81 = t79 - t80
    t82 = ka0_re * t50
    t83 = ka0_im * t49
    t84 = t82 + t83
    t85 = ka0_re * t71
    t86 = ka0_im * t72
    t87 = t85 - t86
    t88 = ka0_re * t72
    t89 = ka0_im * t71
    t90 = t88 + t89
    sp_6 = tl.load(sp_ptr + 6 * n_sites + site, mask=mask)
    sp_18 = tl.load(sp_ptr + 18 * n_sites + site, mask=mask)
    t91 = sp_6 + sp_18
    sp_7 = tl.load(sp_ptr + 7 * n_sites + site, mask=mask)
    sp_19 = tl.load(sp_ptr + 19 * n_sites + site, mask=mask)
    t92 = sp_7 + sp_19
    sp_8 = tl.load(sp_ptr + 8 * n_sites + site, mask=mask)
    sp_20 = tl.load(sp_ptr + 20 * n_sites + site, mask=mask)
    t93 = sp_8 + sp_20
    sp_9 = tl.load(sp_ptr + 9 * n_sites + site, mask=mask)
    sp_21 = tl.load(sp_ptr + 21 * n_sites + site, mask=mask)
    t94 = sp_9 + sp_21
    sp_10 = tl.load(sp_ptr + 10 * n_sites + site, mask=mask)
    sp_22 = tl.load(sp_ptr + 22 * n_sites + site, mask=mask)
    t95 = sp_10 + sp_22
    sp_11 = tl.load(sp_ptr + 11 * n_sites + site, mask=mask)
    sp_23 = tl.load(sp_ptr + 23 * n_sites + site, mask=mask)
    t96 = sp_11 + sp_23
    t97 = u_0 * t91
    t98 = u_1 * t92
    t99 = t97 - t98
    t100 = u_0 * t92
    t101 = u_1 * t91
    t102 = t100 + t101
    t103 = u_2 * t93
    t104 = u_3 * t94
    t105 = t103 - t104
    t106 = u_2 * t94
    t107 = u_3 * t93
    t108 = t106 + t107
    t109 = t99 + t105
    t110 = t102 + t108
    t111 = u_4 * t95
    t112 = u_5 * t96
    t113 = t111 - t112
    t114 = u_4 * t96
    t115 = u_5 * t95
    t116 = t114 + t115
    t117 = t109 + t113
    t118 = t110 + t116
    t119 = u_6 * t91
    t120 = u_7 * t92
    t121 = t119 - t120
    t122 = u_6 * t92
    t123 = u_7 * t91
    t124 = t122 + t123
    t125 = u_8 * t93
    t126 = u_9 * t94
    t127 = t125 - t126
    t128 = u_8 * t94
    t129 = u_9 * t93
    t130 = t128 + t129
    t131 = t121 + t127
    t132 = t124 + t130
    t133 = u_10 * t95
    t134 = u_11 * t96
    t135 = t133 - t134
    t136 = u_10 * t96
    t137 = u_11 * t95
    t138 = t136 + t137
    t139 = t131 + t135
    t140 = t132 + t138
    t141 = u_12 * t91
    t142 = u_13 * t92
    t143 = t141 - t142
    t144 = u_12 * t92
    t145 = u_13 * t91
    t146 = t144 + t145
    t147 = u_14 * t93
    t148 = u_15 * t94
    t149 = t147 - t148
    t150 = u_14 * t94
    t151 = u_15 * t93
    t152 = t150 + t151
    t153 = t143 + t149
    t154 = t146 + t152
    t155 = u_16 * t95
    t156 = u_17 * t96
    t157 = t155 - t156
    t158 = u_16 * t96
    t159 = u_17 * t95
    t160 = t158 + t159
    t161 = t153 + t157
    t162 = t154 + t160
    t163 = ka0_re * t117
    t164 = ka0_im * t118
    t165 = t163 - t164
    t166 = ka0_re * t118
    t167 = ka0_im * t117
    t168 = t166 + t167
    t169 = ka0_re * t139
    t170 = ka0_im * t140
    t171 = t169 - t170
    t172 = ka0_re * t140
    t173 = ka0_im * t139
    t174 = t172 + t173
    t175 = ka0_re * t161
    t176 = ka0_im * t162
    t177 = t175 - t176
    t178 = ka0_re * t162
    t179 = ka0_im * t161
    t180 = t178 + t179
    tl.store(out_ptr + 0 * n_sites + site, t75, mask=mask)
    tl.store(out_ptr + 1 * n_sites + site, t78, mask=mask)
    tl.store(out_ptr + 2 * n_sites + site, t81, mask=mask)
    tl.store(out_ptr + 3 * n_sites + site, t84, mask=mask)
    tl.store(out_ptr + 4 * n_sites + site, t87, mask=mask)
    tl.store(out_ptr + 5 * n_sites + site, t90, mask=mask)
    tl.store(out_ptr + 6 * n_sites + site, t165, mask=mask)
    tl.store(out_ptr + 7 * n_sites + site, t168, mask=mask)
    tl.store(out_ptr + 8 * n_sites + site, t171, mask=mask)
    tl.store(out_ptr + 9 * n_sites + site, t174, mask=mask)
    tl.store(out_ptr + 10 * n_sites + site, t177, mask=mask)
    tl.store(out_ptr + 11 * n_sites + site, t180, mask=mask)
    tl.store(out_ptr + 12 * n_sites + site, t75, mask=mask)
    tl.store(out_ptr + 13 * n_sites + site, t78, mask=mask)
    tl.store(out_ptr + 14 * n_sites + site, t81, mask=mask)
    tl.store(out_ptr + 15 * n_sites + site, t84, mask=mask)
    tl.store(out_ptr + 16 * n_sites + site, t87, mask=mask)
    tl.store(out_ptr + 17 * n_sites + site, t90, mask=mask)
    tl.store(out_ptr + 18 * n_sites + site, t165, mask=mask)
    tl.store(out_ptr + 19 * n_sites + site, t168, mask=mask)
    tl.store(out_ptr + 20 * n_sites + site, t171, mask=mask)
    tl.store(out_ptr + 21 * n_sites + site, t174, mask=mask)
    tl.store(out_ptr + 22 * n_sites + site, t177, mask=mask)
    tl.store(out_ptr + 23 * n_sites + site, t180, mask=mask)


torch.manual_seed(0)
n_sites = 4096
triton.runtime.driver.set_active_to_cpu()
values = torch.tensor([-3.0, -2.0, -1.0, 1.0, 2.0, 3.0])
sp = values[torch.randint(0, len(values), (24, n_sites))]
u = values[torch.randint(0, len(values), (18, n_sites))]
ka0_re = 2.0
ka0_im = -1.0
from triton.backends.cpu.riscv import compile_deploy_and_run

RISCV_HOST = "chlee@140.114.78.64"
RISCV_REMOTE_DIR = "~/triton-riscv-elf"


def reference():

    sp_0 = sp[0]
    sp_12 = sp[12]
    t1 = sp_0 + sp_12
    sp_1 = sp[1]
    sp_13 = sp[13]
    t2 = sp_1 + sp_13
    sp_2 = sp[2]
    sp_14 = sp[14]
    t3 = sp_2 + sp_14
    sp_3 = sp[3]
    sp_15 = sp[15]
    t4 = sp_3 + sp_15
    sp_4 = sp[4]
    sp_16 = sp[16]
    t5 = sp_4 + sp_16
    sp_5 = sp[5]
    sp_17 = sp[17]
    t6 = sp_5 + sp_17
    u_0 = u[0]
    t7 = u_0 * t1
    u_1 = u[1]
    t8 = u_1 * t2
    t9 = t7 - t8
    t10 = u_0 * t2
    t11 = u_1 * t1
    t12 = t10 + t11
    u_2 = u[2]
    t13 = u_2 * t3
    u_3 = u[3]
    t14 = u_3 * t4
    t15 = t13 - t14
    t16 = u_2 * t4
    t17 = u_3 * t3
    t18 = t16 + t17
    t19 = t9 + t15
    t20 = t12 + t18
    u_4 = u[4]
    t21 = u_4 * t5
    u_5 = u[5]
    t22 = u_5 * t6
    t23 = t21 - t22
    t24 = u_4 * t6
    t25 = u_5 * t5
    t26 = t24 + t25
    t27 = t19 + t23
    t28 = t20 + t26
    u_6 = u[6]
    t29 = u_6 * t1
    u_7 = u[7]
    t30 = u_7 * t2
    t31 = t29 - t30
    t32 = u_6 * t2
    t33 = u_7 * t1
    t34 = t32 + t33
    u_8 = u[8]
    t35 = u_8 * t3
    u_9 = u[9]
    t36 = u_9 * t4
    t37 = t35 - t36
    t38 = u_8 * t4
    t39 = u_9 * t3
    t40 = t38 + t39
    t41 = t31 + t37
    t42 = t34 + t40
    u_10 = u[10]
    t43 = u_10 * t5
    u_11 = u[11]
    t44 = u_11 * t6
    t45 = t43 - t44
    t46 = u_10 * t6
    t47 = u_11 * t5
    t48 = t46 + t47
    t49 = t41 + t45
    t50 = t42 + t48
    u_12 = u[12]
    t51 = u_12 * t1
    u_13 = u[13]
    t52 = u_13 * t2
    t53 = t51 - t52
    t54 = u_12 * t2
    t55 = u_13 * t1
    t56 = t54 + t55
    u_14 = u[14]
    t57 = u_14 * t3
    u_15 = u[15]
    t58 = u_15 * t4
    t59 = t57 - t58
    t60 = u_14 * t4
    t61 = u_15 * t3
    t62 = t60 + t61
    t63 = t53 + t59
    t64 = t56 + t62
    u_16 = u[16]
    t65 = u_16 * t5
    u_17 = u[17]
    t66 = u_17 * t6
    t67 = t65 - t66
    t68 = u_16 * t6
    t69 = u_17 * t5
    t70 = t68 + t69
    t71 = t63 + t67
    t72 = t64 + t70
    t73 = ka0_re * t27
    t74 = ka0_im * t28
    t75 = t73 - t74
    t76 = ka0_re * t28
    t77 = ka0_im * t27
    t78 = t76 + t77
    t79 = ka0_re * t49
    t80 = ka0_im * t50
    t81 = t79 - t80
    t82 = ka0_re * t50
    t83 = ka0_im * t49
    t84 = t82 + t83
    t85 = ka0_re * t71
    t86 = ka0_im * t72
    t87 = t85 - t86
    t88 = ka0_re * t72
    t89 = ka0_im * t71
    t90 = t88 + t89
    sp_6 = sp[6]
    sp_18 = sp[18]
    t91 = sp_6 + sp_18
    sp_7 = sp[7]
    sp_19 = sp[19]
    t92 = sp_7 + sp_19
    sp_8 = sp[8]
    sp_20 = sp[20]
    t93 = sp_8 + sp_20
    sp_9 = sp[9]
    sp_21 = sp[21]
    t94 = sp_9 + sp_21
    sp_10 = sp[10]
    sp_22 = sp[22]
    t95 = sp_10 + sp_22
    sp_11 = sp[11]
    sp_23 = sp[23]
    t96 = sp_11 + sp_23
    t97 = u_0 * t91
    t98 = u_1 * t92
    t99 = t97 - t98
    t100 = u_0 * t92
    t101 = u_1 * t91
    t102 = t100 + t101
    t103 = u_2 * t93
    t104 = u_3 * t94
    t105 = t103 - t104
    t106 = u_2 * t94
    t107 = u_3 * t93
    t108 = t106 + t107
    t109 = t99 + t105
    t110 = t102 + t108
    t111 = u_4 * t95
    t112 = u_5 * t96
    t113 = t111 - t112
    t114 = u_4 * t96
    t115 = u_5 * t95
    t116 = t114 + t115
    t117 = t109 + t113
    t118 = t110 + t116
    t119 = u_6 * t91
    t120 = u_7 * t92
    t121 = t119 - t120
    t122 = u_6 * t92
    t123 = u_7 * t91
    t124 = t122 + t123
    t125 = u_8 * t93
    t126 = u_9 * t94
    t127 = t125 - t126
    t128 = u_8 * t94
    t129 = u_9 * t93
    t130 = t128 + t129
    t131 = t121 + t127
    t132 = t124 + t130
    t133 = u_10 * t95
    t134 = u_11 * t96
    t135 = t133 - t134
    t136 = u_10 * t96
    t137 = u_11 * t95
    t138 = t136 + t137
    t139 = t131 + t135
    t140 = t132 + t138
    t141 = u_12 * t91
    t142 = u_13 * t92
    t143 = t141 - t142
    t144 = u_12 * t92
    t145 = u_13 * t91
    t146 = t144 + t145
    t147 = u_14 * t93
    t148 = u_15 * t94
    t149 = t147 - t148
    t150 = u_14 * t94
    t151 = u_15 * t93
    t152 = t150 + t151
    t153 = t143 + t149
    t154 = t146 + t152
    t155 = u_16 * t95
    t156 = u_17 * t96
    t157 = t155 - t156
    t158 = u_16 * t96
    t159 = u_17 * t95
    t160 = t158 + t159
    t161 = t153 + t157
    t162 = t154 + t160
    t163 = ka0_re * t117
    t164 = ka0_im * t118
    t165 = t163 - t164
    t166 = ka0_re * t118
    t167 = ka0_im * t117
    t168 = t166 + t167
    t169 = ka0_re * t139
    t170 = ka0_im * t140
    t171 = t169 - t170
    t172 = ka0_re * t140
    t173 = ka0_im * t139
    t174 = t172 + t173
    t175 = ka0_re * t161
    t176 = ka0_im * t162
    t177 = t175 - t176
    t178 = ka0_re * t162
    t179 = ka0_im * t161
    t180 = t178 + t179
    return torch.stack([t75, t78, t81, t84, t87, t90, t165, t168, t171, t174, t177, t180, t75, t78, t81, t84, t87, t90, t165, t168, t171, t174, t177, t180])


def run_on_board(kernel, constexprs, name):
    expected = reference().reshape(-1)
    arguments = {
        "sp_ptr": sp.reshape(-1).tolist(),
        "u_ptr": u.reshape(-1).tolist(),
        "out_ptr": [0.0] * (24 * n_sites),
        "n_sites": n_sites,
        "ka0_re": ka0_re,
        "ka0_im": ka0_im,
    }
    grid = (triton.cdiv(n_sites, CPU_BLOCK_SIZE), )
    result = compile_deploy_and_run(kernel, arguments, grid, f"artifacts/riscv/{name}.elf", RISCV_HOST,
                                     constexprs=constexprs, expected={"out_ptr": expected.tolist()},
                                     remote_dir=RISCV_REMOTE_DIR)
    print(f"{name}:")
    print(result.stdout, end="")
    print(result.stderr, end="")


run_on_board(lqcd_hop_t_p_kernel, {"BLOCK_SIZE": CPU_BLOCK_SIZE}, "rvv-lqcd-hop-t-p")
