"""
tmLQCD hop_t_m, vectorized over lattice sites
====================================================
Hopping_Matrix loop l body, _hop_t_m (src/lib/operator/hopping.h):
    psi = sm.s0 - sm.s2; chi = um^dagger * psi; psi = conj(ka0) * chi; temp.s0 += psi; temp.s2 -= psi
    psi = sm.s1 - sm.s3; chi = um^dagger * psi; psi = conj(ka0) * chi; temp.s1 += psi; temp.s3 -= psi

Generated by gen_rvv_lqcd.py (see there for the sources). One lattice site per
lane; every real or imaginary part is a 64-lane f32 vector, one LMUL8
register group at VLEN 256, loaded from plane p of a structure-of-arrays field
(field_ptr + p * n_sites + site). Inputs are small nonzero integers so the
float results are exact and the torch reference matches bit for bit.
"""

import torch

import triton
import triton.language as tl

CPU_BLOCK_SIZE = 64


@triton.jit
def lqcd_hop_t_m_kernel(sm_ptr, um_ptr, tin_ptr, out_ptr, n_sites, ka0_re, ka0_im, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    site = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = site < n_sites

    sm_0 = tl.load(sm_ptr + 0 * n_sites + site, mask=mask)
    sm_12 = tl.load(sm_ptr + 12 * n_sites + site, mask=mask)
    t1 = sm_0 - sm_12
    sm_1 = tl.load(sm_ptr + 1 * n_sites + site, mask=mask)
    sm_13 = tl.load(sm_ptr + 13 * n_sites + site, mask=mask)
    t2 = sm_1 - sm_13
    sm_2 = tl.load(sm_ptr + 2 * n_sites + site, mask=mask)
    sm_14 = tl.load(sm_ptr + 14 * n_sites + site, mask=mask)
    t3 = sm_2 - sm_14
    sm_3 = tl.load(sm_ptr + 3 * n_sites + site, mask=mask)
    sm_15 = tl.load(sm_ptr + 15 * n_sites + site, mask=mask)
    t4 = sm_3 - sm_15
    sm_4 = tl.load(sm_ptr + 4 * n_sites + site, mask=mask)
    sm_16 = tl.load(sm_ptr + 16 * n_sites + site, mask=mask)
    t5 = sm_4 - sm_16
    sm_5 = tl.load(sm_ptr + 5 * n_sites + site, mask=mask)
    sm_17 = tl.load(sm_ptr + 17 * n_sites + site, mask=mask)
    t6 = sm_5 - sm_17
    um_0 = tl.load(um_ptr + 0 * n_sites + site, mask=mask)
    t7 = um_0 * t1
    um_1 = tl.load(um_ptr + 1 * n_sites + site, mask=mask)
    t8 = um_1 * t2
    t9 = t7 + t8
    t10 = um_0 * t2
    t11 = um_1 * t1
    t12 = t10 - t11
    um_6 = tl.load(um_ptr + 6 * n_sites + site, mask=mask)
    t13 = um_6 * t3
    um_7 = tl.load(um_ptr + 7 * n_sites + site, mask=mask)
    t14 = um_7 * t4
    t15 = t13 + t14
    t16 = um_6 * t4
    t17 = um_7 * t3
    t18 = t16 - t17
    t19 = t9 + t15
    t20 = t12 + t18
    um_12 = tl.load(um_ptr + 12 * n_sites + site, mask=mask)
    t21 = um_12 * t5
    um_13 = tl.load(um_ptr + 13 * n_sites + site, mask=mask)
    t22 = um_13 * t6
    t23 = t21 + t22
    t24 = um_12 * t6
    t25 = um_13 * t5
    t26 = t24 - t25
    t27 = t19 + t23
    t28 = t20 + t26
    um_2 = tl.load(um_ptr + 2 * n_sites + site, mask=mask)
    t29 = um_2 * t1
    um_3 = tl.load(um_ptr + 3 * n_sites + site, mask=mask)
    t30 = um_3 * t2
    t31 = t29 + t30
    t32 = um_2 * t2
    t33 = um_3 * t1
    t34 = t32 - t33
    um_8 = tl.load(um_ptr + 8 * n_sites + site, mask=mask)
    t35 = um_8 * t3
    um_9 = tl.load(um_ptr + 9 * n_sites + site, mask=mask)
    t36 = um_9 * t4
    t37 = t35 + t36
    t38 = um_8 * t4
    t39 = um_9 * t3
    t40 = t38 - t39
    t41 = t31 + t37
    t42 = t34 + t40
    um_14 = tl.load(um_ptr + 14 * n_sites + site, mask=mask)
    t43 = um_14 * t5
    um_15 = tl.load(um_ptr + 15 * n_sites + site, mask=mask)
    t44 = um_15 * t6
    t45 = t43 + t44
    t46 = um_14 * t6
    t47 = um_15 * t5
    t48 = t46 - t47
    t49 = t41 + t45
    t50 = t42 + t48
    um_4 = tl.load(um_ptr + 4 * n_sites + site, mask=mask)
    t51 = um_4 * t1
    um_5 = tl.load(um_ptr + 5 * n_sites + site, mask=mask)
    t52 = um_5 * t2
    t53 = t51 + t52
    t54 = um_4 * t2
    t55 = um_5 * t1
    t56 = t54 - t55
    um_10 = tl.load(um_ptr + 10 * n_sites + site, mask=mask)
    t57 = um_10 * t3
    um_11 = tl.load(um_ptr + 11 * n_sites + site, mask=mask)
    t58 = um_11 * t4
    t59 = t57 + t58
    t60 = um_10 * t4
    t61 = um_11 * t3
    t62 = t60 - t61
    t63 = t53 + t59
    t64 = t56 + t62
    um_16 = tl.load(um_ptr + 16 * n_sites + site, mask=mask)
    t65 = um_16 * t5
    um_17 = tl.load(um_ptr + 17 * n_sites + site, mask=mask)
    t66 = um_17 * t6
    t67 = t65 + t66
    t68 = um_16 * t6
    t69 = um_17 * t5
    t70 = t68 - t69
    t71 = t63 + t67
    t72 = t64 + t70
    t73 = ka0_re * t27
    t74 = ka0_im * t28
    t75 = t73 + t74
    t76 = ka0_re * t28
    t77 = ka0_im * t27
    t78 = t76 - t77
    t79 = ka0_re * t49
    t80 = ka0_im * t50
    t81 = t79 + t80
    t82 = ka0_re * t50
    t83 = ka0_im * t49
    t84 = t82 - t83
    t85 = ka0_re * t71
    t86 = ka0_im * t72
    t87 = t85 + t86
    t88 = ka0_re * t72
    t89 = ka0_im * t71
    t90 = t88 - t89
    tin_0 = tl.load(tin_ptr + 0 * n_sites + site, mask=mask)
    t91 = tin_0 + t75
    tin_1 = tl.load(tin_ptr + 1 * n_sites + site, mask=mask)
    t92 = tin_1 + t78
    tin_2 = tl.load(tin_ptr + 2 * n_sites + site, mask=mask)
    t93 = tin_2 + t81
    tin_3 = tl.load(tin_ptr + 3 * n_sites + site, mask=mask)
    t94 = tin_3 + t84
    tin_4 = tl.load(tin_ptr + 4 * n_sites + site, mask=mask)
    t95 = tin_4 + t87
    tin_5 = tl.load(tin_ptr + 5 * n_sites + site, mask=mask)
    t96 = tin_5 + t90
    tin_12 = tl.load(tin_ptr + 12 * n_sites + site, mask=mask)
    t97 = tin_12 - t75
    tin_13 = tl.load(tin_ptr + 13 * n_sites + site, mask=mask)
    t98 = tin_13 - t78
    tin_14 = tl.load(tin_ptr + 14 * n_sites + site, mask=mask)
    t99 = tin_14 - t81
    tin_15 = tl.load(tin_ptr + 15 * n_sites + site, mask=mask)
    t100 = tin_15 - t84
    tin_16 = tl.load(tin_ptr + 16 * n_sites + site, mask=mask)
    t101 = tin_16 - t87
    tin_17 = tl.load(tin_ptr + 17 * n_sites + site, mask=mask)
    t102 = tin_17 - t90
    sm_6 = tl.load(sm_ptr + 6 * n_sites + site, mask=mask)
    sm_18 = tl.load(sm_ptr + 18 * n_sites + site, mask=mask)
    t103 = sm_6 - sm_18
    sm_7 = tl.load(sm_ptr + 7 * n_sites + site, mask=mask)
    sm_19 = tl.load(sm_ptr + 19 * n_sites + site, mask=mask)
    t104 = sm_7 - sm_19
    sm_8 = tl.load(sm_ptr + 8 * n_sites + site, mask=mask)
    sm_20 = tl.load(sm_ptr + 20 * n_sites + site, mask=mask)
    t105 = sm_8 - sm_20
    sm_9 = tl.load(sm_ptr + 9 * n_sites + site, mask=mask)
    sm_21 = tl.load(sm_ptr + 21 * n_sites + site, mask=mask)
    t106 = sm_9 - sm_21
    sm_10 = tl.load(sm_ptr + 10 * n_sites + site, mask=mask)
    sm_22 = tl.load(sm_ptr + 22 * n_sites + site, mask=mask)
    t107 = sm_10 - sm_22
    sm_11 = tl.load(sm_ptr + 11 * n_sites + site, mask=mask)
    sm_23 = tl.load(sm_ptr + 23 * n_sites + site, mask=mask)
    t108 = sm_11 - sm_23
    t109 = um_0 * t103
    t110 = um_1 * t104
    t111 = t109 + t110
    t112 = um_0 * t104
    t113 = um_1 * t103
    t114 = t112 - t113
    t115 = um_6 * t105
    t116 = um_7 * t106
    t117 = t115 + t116
    t118 = um_6 * t106
    t119 = um_7 * t105
    t120 = t118 - t119
    t121 = t111 + t117
    t122 = t114 + t120
    t123 = um_12 * t107
    t124 = um_13 * t108
    t125 = t123 + t124
    t126 = um_12 * t108
    t127 = um_13 * t107
    t128 = t126 - t127
    t129 = t121 + t125
    t130 = t122 + t128
    t131 = um_2 * t103
    t132 = um_3 * t104
    t133 = t131 + t132
    t134 = um_2 * t104
    t135 = um_3 * t103
    t136 = t134 - t135
    t137 = um_8 * t105
    t138 = um_9 * t106
    t139 = t137 + t138
    t140 = um_8 * t106
    t141 = um_9 * t105
    t142 = t140 - t141
    t143 = t133 + t139
    t144 = t136 + t142
    t145 = um_14 * t107
    t146 = um_15 * t108
    t147 = t145 + t146
    t148 = um_14 * t108
    t149 = um_15 * t107
    t150 = t148 - t149
    t151 = t143 + t147
    t152 = t144 + t150
    t153 = um_4 * t103
    t154 = um_5 * t104
    t155 = t153 + t154
    t156 = um_4 * t104
    t157 = um_5 * t103
    t158 = t156 - t157
    t159 = um_10 * t105
    t160 = um_11 * t106
    t161 = t159 + t160
    t162 = um_10 * t106
    t163 = um_11 * t105
    t164 = t162 - t163
    t165 = t155 + t161
    t166 = t158 + t164
    t167 = um_16 * t107
    t168 = um_17 * t108
    t169 = t167 + t168
    t170 = um_16 * t108
    t171 = um_17 * t107
    t172 = t170 - t171
    t173 = t165 + t169
    t174 = t166 + t172
    t175 = ka0_re * t129
    t176 = ka0_im * t130
    t177 = t175 + t176
    t178 = ka0_re * t130
    t179 = ka0_im * t129
    t180 = t178 - t179
    t181 = ka0_re * t151
    t182 = ka0_im * t152
    t183 = t181 + t182
    t184 = ka0_re * t152
    t185 = ka0_im * t151
    t186 = t184 - t185
    t187 = ka0_re * t173
    t188 = ka0_im * t174
    t189 = t187 + t188
    t190 = ka0_re * t174
    t191 = ka0_im * t173
    t192 = t190 - t191
    tin_6 = tl.load(tin_ptr + 6 * n_sites + site, mask=mask)
    t193 = tin_6 + t177
    tin_7 = tl.load(tin_ptr + 7 * n_sites + site, mask=mask)
    t194 = tin_7 + t180
    tin_8 = tl.load(tin_ptr + 8 * n_sites + site, mask=mask)
    t195 = tin_8 + t183
    tin_9 = tl.load(tin_ptr + 9 * n_sites + site, mask=mask)
    t196 = tin_9 + t186
    tin_10 = tl.load(tin_ptr + 10 * n_sites + site, mask=mask)
    t197 = tin_10 + t189
    tin_11 = tl.load(tin_ptr + 11 * n_sites + site, mask=mask)
    t198 = tin_11 + t192
    tin_18 = tl.load(tin_ptr + 18 * n_sites + site, mask=mask)
    t199 = tin_18 - t177
    tin_19 = tl.load(tin_ptr + 19 * n_sites + site, mask=mask)
    t200 = tin_19 - t180
    tin_20 = tl.load(tin_ptr + 20 * n_sites + site, mask=mask)
    t201 = tin_20 - t183
    tin_21 = tl.load(tin_ptr + 21 * n_sites + site, mask=mask)
    t202 = tin_21 - t186
    tin_22 = tl.load(tin_ptr + 22 * n_sites + site, mask=mask)
    t203 = tin_22 - t189
    tin_23 = tl.load(tin_ptr + 23 * n_sites + site, mask=mask)
    t204 = tin_23 - t192
    tl.store(out_ptr + 0 * n_sites + site, t91, mask=mask)
    tl.store(out_ptr + 1 * n_sites + site, t92, mask=mask)
    tl.store(out_ptr + 2 * n_sites + site, t93, mask=mask)
    tl.store(out_ptr + 3 * n_sites + site, t94, mask=mask)
    tl.store(out_ptr + 4 * n_sites + site, t95, mask=mask)
    tl.store(out_ptr + 5 * n_sites + site, t96, mask=mask)
    tl.store(out_ptr + 6 * n_sites + site, t193, mask=mask)
    tl.store(out_ptr + 7 * n_sites + site, t194, mask=mask)
    tl.store(out_ptr + 8 * n_sites + site, t195, mask=mask)
    tl.store(out_ptr + 9 * n_sites + site, t196, mask=mask)
    tl.store(out_ptr + 10 * n_sites + site, t197, mask=mask)
    tl.store(out_ptr + 11 * n_sites + site, t198, mask=mask)
    tl.store(out_ptr + 12 * n_sites + site, t97, mask=mask)
    tl.store(out_ptr + 13 * n_sites + site, t98, mask=mask)
    tl.store(out_ptr + 14 * n_sites + site, t99, mask=mask)
    tl.store(out_ptr + 15 * n_sites + site, t100, mask=mask)
    tl.store(out_ptr + 16 * n_sites + site, t101, mask=mask)
    tl.store(out_ptr + 17 * n_sites + site, t102, mask=mask)
    tl.store(out_ptr + 18 * n_sites + site, t199, mask=mask)
    tl.store(out_ptr + 19 * n_sites + site, t200, mask=mask)
    tl.store(out_ptr + 20 * n_sites + site, t201, mask=mask)
    tl.store(out_ptr + 21 * n_sites + site, t202, mask=mask)
    tl.store(out_ptr + 22 * n_sites + site, t203, mask=mask)
    tl.store(out_ptr + 23 * n_sites + site, t204, mask=mask)


torch.manual_seed(0)
n_sites = 4096
triton.runtime.driver.set_active_to_cpu()
values = torch.tensor([-3.0, -2.0, -1.0, 1.0, 2.0, 3.0])
sm = values[torch.randint(0, len(values), (24, n_sites))]
um = values[torch.randint(0, len(values), (18, n_sites))]
tin = values[torch.randint(0, len(values), (24, n_sites))]
ka0_re = 2.0
ka0_im = -1.0
from triton.backends.cpu.riscv import compile_deploy_and_run

RISCV_HOST = "chlee@140.114.78.64"
RISCV_REMOTE_DIR = "~/triton-riscv-elf"


def reference():

    sm_0 = sm[0]
    sm_12 = sm[12]
    t1 = sm_0 - sm_12
    sm_1 = sm[1]
    sm_13 = sm[13]
    t2 = sm_1 - sm_13
    sm_2 = sm[2]
    sm_14 = sm[14]
    t3 = sm_2 - sm_14
    sm_3 = sm[3]
    sm_15 = sm[15]
    t4 = sm_3 - sm_15
    sm_4 = sm[4]
    sm_16 = sm[16]
    t5 = sm_4 - sm_16
    sm_5 = sm[5]
    sm_17 = sm[17]
    t6 = sm_5 - sm_17
    um_0 = um[0]
    t7 = um_0 * t1
    um_1 = um[1]
    t8 = um_1 * t2
    t9 = t7 + t8
    t10 = um_0 * t2
    t11 = um_1 * t1
    t12 = t10 - t11
    um_6 = um[6]
    t13 = um_6 * t3
    um_7 = um[7]
    t14 = um_7 * t4
    t15 = t13 + t14
    t16 = um_6 * t4
    t17 = um_7 * t3
    t18 = t16 - t17
    t19 = t9 + t15
    t20 = t12 + t18
    um_12 = um[12]
    t21 = um_12 * t5
    um_13 = um[13]
    t22 = um_13 * t6
    t23 = t21 + t22
    t24 = um_12 * t6
    t25 = um_13 * t5
    t26 = t24 - t25
    t27 = t19 + t23
    t28 = t20 + t26
    um_2 = um[2]
    t29 = um_2 * t1
    um_3 = um[3]
    t30 = um_3 * t2
    t31 = t29 + t30
    t32 = um_2 * t2
    t33 = um_3 * t1
    t34 = t32 - t33
    um_8 = um[8]
    t35 = um_8 * t3
    um_9 = um[9]
    t36 = um_9 * t4
    t37 = t35 + t36
    t38 = um_8 * t4
    t39 = um_9 * t3
    t40 = t38 - t39
    t41 = t31 + t37
    t42 = t34 + t40
    um_14 = um[14]
    t43 = um_14 * t5
    um_15 = um[15]
    t44 = um_15 * t6
    t45 = t43 + t44
    t46 = um_14 * t6
    t47 = um_15 * t5
    t48 = t46 - t47
    t49 = t41 + t45
    t50 = t42 + t48
    um_4 = um[4]
    t51 = um_4 * t1
    um_5 = um[5]
    t52 = um_5 * t2
    t53 = t51 + t52
    t54 = um_4 * t2
    t55 = um_5 * t1
    t56 = t54 - t55
    um_10 = um[10]
    t57 = um_10 * t3
    um_11 = um[11]
    t58 = um_11 * t4
    t59 = t57 + t58
    t60 = um_10 * t4
    t61 = um_11 * t3
    t62 = t60 - t61
    t63 = t53 + t59
    t64 = t56 + t62
    um_16 = um[16]
    t65 = um_16 * t5
    um_17 = um[17]
    t66 = um_17 * t6
    t67 = t65 + t66
    t68 = um_16 * t6
    t69 = um_17 * t5
    t70 = t68 - t69
    t71 = t63 + t67
    t72 = t64 + t70
    t73 = ka0_re * t27
    t74 = ka0_im * t28
    t75 = t73 + t74
    t76 = ka0_re * t28
    t77 = ka0_im * t27
    t78 = t76 - t77
    t79 = ka0_re * t49
    t80 = ka0_im * t50
    t81 = t79 + t80
    t82 = ka0_re * t50
    t83 = ka0_im * t49
    t84 = t82 - t83
    t85 = ka0_re * t71
    t86 = ka0_im * t72
    t87 = t85 + t86
    t88 = ka0_re * t72
    t89 = ka0_im * t71
    t90 = t88 - t89
    tin_0 = tin[0]
    t91 = tin_0 + t75
    tin_1 = tin[1]
    t92 = tin_1 + t78
    tin_2 = tin[2]
    t93 = tin_2 + t81
    tin_3 = tin[3]
    t94 = tin_3 + t84
    tin_4 = tin[4]
    t95 = tin_4 + t87
    tin_5 = tin[5]
    t96 = tin_5 + t90
    tin_12 = tin[12]
    t97 = tin_12 - t75
    tin_13 = tin[13]
    t98 = tin_13 - t78
    tin_14 = tin[14]
    t99 = tin_14 - t81
    tin_15 = tin[15]
    t100 = tin_15 - t84
    tin_16 = tin[16]
    t101 = tin_16 - t87
    tin_17 = tin[17]
    t102 = tin_17 - t90
    sm_6 = sm[6]
    sm_18 = sm[18]
    t103 = sm_6 - sm_18
    sm_7 = sm[7]
    sm_19 = sm[19]
    t104 = sm_7 - sm_19
    sm_8 = sm[8]
    sm_20 = sm[20]
    t105 = sm_8 - sm_20
    sm_9 = sm[9]
    sm_21 = sm[21]
    t106 = sm_9 - sm_21
    sm_10 = sm[10]
    sm_22 = sm[22]
    t107 = sm_10 - sm_22
    sm_11 = sm[11]
    sm_23 = sm[23]
    t108 = sm_11 - sm_23
    t109 = um_0 * t103
    t110 = um_1 * t104
    t111 = t109 + t110
    t112 = um_0 * t104
    t113 = um_1 * t103
    t114 = t112 - t113
    t115 = um_6 * t105
    t116 = um_7 * t106
    t117 = t115 + t116
    t118 = um_6 * t106
    t119 = um_7 * t105
    t120 = t118 - t119
    t121 = t111 + t117
    t122 = t114 + t120
    t123 = um_12 * t107
    t124 = um_13 * t108
    t125 = t123 + t124
    t126 = um_12 * t108
    t127 = um_13 * t107
    t128 = t126 - t127
    t129 = t121 + t125
    t130 = t122 + t128
    t131 = um_2 * t103
    t132 = um_3 * t104
    t133 = t131 + t132
    t134 = um_2 * t104
    t135 = um_3 * t103
    t136 = t134 - t135
    t137 = um_8 * t105
    t138 = um_9 * t106
    t139 = t137 + t138
    t140 = um_8 * t106
    t141 = um_9 * t105
    t142 = t140 - t141
    t143 = t133 + t139
    t144 = t136 + t142
    t145 = um_14 * t107
    t146 = um_15 * t108
    t147 = t145 + t146
    t148 = um_14 * t108
    t149 = um_15 * t107
    t150 = t148 - t149
    t151 = t143 + t147
    t152 = t144 + t150
    t153 = um_4 * t103
    t154 = um_5 * t104
    t155 = t153 + t154
    t156 = um_4 * t104
    t157 = um_5 * t103
    t158 = t156 - t157
    t159 = um_10 * t105
    t160 = um_11 * t106
    t161 = t159 + t160
    t162 = um_10 * t106
    t163 = um_11 * t105
    t164 = t162 - t163
    t165 = t155 + t161
    t166 = t158 + t164
    t167 = um_16 * t107
    t168 = um_17 * t108
    t169 = t167 + t168
    t170 = um_16 * t108
    t171 = um_17 * t107
    t172 = t170 - t171
    t173 = t165 + t169
    t174 = t166 + t172
    t175 = ka0_re * t129
    t176 = ka0_im * t130
    t177 = t175 + t176
    t178 = ka0_re * t130
    t179 = ka0_im * t129
    t180 = t178 - t179
    t181 = ka0_re * t151
    t182 = ka0_im * t152
    t183 = t181 + t182
    t184 = ka0_re * t152
    t185 = ka0_im * t151
    t186 = t184 - t185
    t187 = ka0_re * t173
    t188 = ka0_im * t174
    t189 = t187 + t188
    t190 = ka0_re * t174
    t191 = ka0_im * t173
    t192 = t190 - t191
    tin_6 = tin[6]
    t193 = tin_6 + t177
    tin_7 = tin[7]
    t194 = tin_7 + t180
    tin_8 = tin[8]
    t195 = tin_8 + t183
    tin_9 = tin[9]
    t196 = tin_9 + t186
    tin_10 = tin[10]
    t197 = tin_10 + t189
    tin_11 = tin[11]
    t198 = tin_11 + t192
    tin_18 = tin[18]
    t199 = tin_18 - t177
    tin_19 = tin[19]
    t200 = tin_19 - t180
    tin_20 = tin[20]
    t201 = tin_20 - t183
    tin_21 = tin[21]
    t202 = tin_21 - t186
    tin_22 = tin[22]
    t203 = tin_22 - t189
    tin_23 = tin[23]
    t204 = tin_23 - t192
    return torch.stack([t91, t92, t93, t94, t95, t96, t193, t194, t195, t196, t197, t198, t97, t98, t99, t100, t101, t102, t199, t200, t201, t202, t203, t204])


def run_on_board(kernel, constexprs, name):
    expected = reference().reshape(-1)
    arguments = {
        "sm_ptr": sm.reshape(-1).tolist(),
        "um_ptr": um.reshape(-1).tolist(),
        "tin_ptr": tin.reshape(-1).tolist(),
        "out_ptr": [0.0] * (24 * n_sites),
        "n_sites": n_sites,
        "ka0_re": ka0_re,
        "ka0_im": ka0_im,
    }
    grid = (triton.cdiv(n_sites, CPU_BLOCK_SIZE), )
    result = compile_deploy_and_run(kernel, arguments, grid, f"artifacts/riscv/{name}.elf", RISCV_HOST,
                                     constexprs=constexprs, expected={"out_ptr": expected.tolist()},
                                     remote_dir=RISCV_REMOTE_DIR)
    print(f"{name}:")
    print(result.stdout, end="")
    print(result.stderr, end="")


run_on_board(lqcd_hop_t_m_kernel, {"BLOCK_SIZE": CPU_BLOCK_SIZE}, "rvv-lqcd-hop-t-m")
